    INSERT INTO `miempresa`.`clientes` (`nombre`, `apellidos`, `email`, `poblacion`, `fechadenacimiento`) VALUES
    ('Juan', 'Pérez López', 'juan.perez@example.com', 'Madrid', '1985-03-15'),
    ('María', 'González Sánchez', 'maria.gonzalez@example.com', 'Barcelona', '1990-07-22'),
    ('Carlos', 'Rodríguez Fernández', 'carlos.rodriguez@example.com', 'Valencia', '1982-01-30'),
    ('Ana', 'Martínez Gómez', 'ana.martinez@example.com', 'Sevilla', '1993-10-11'),
    ('Luis', 'Hernández Díaz', 'luis.hernandez@example.com', 'Bilbao', '1978-05-09'),
    ('Laura', 'Jiménez Pérez', 'laura.jimenez@example.com', 'Zaragoza', '1995-02-25'),
    ('Jorge', 'López Romero', 'jorge.lopez@example.com', 'Granada', '1987-08-18'),
    ('Elena', 'Sanz Torres', 'elena.sanz@example.com', 'Málaga', '1991-12-05'),
    ('Raúl', 'García Martín', 'raul.garcia@example.com', 'Salamanca', '1983-04-14'),
    ('Patricia', 'Vega Ruiz', 'patricia.vega@example.com', 'Valladolid', '1989-09-29'),
    ('Sofía', 'Alonso Ruiz', 'sofia.alonso@example.com', 'Alicante', '1994-11-12'),
    ('Andrés', 'Cruz Morales', 'andres.cruz@example.com', 'Córdoba', '1981-03-23'),
    ('Isabel', 'Muñoz Castillo', 'isabel.munoz@example.com', 'Murcia', '1992-06-17'),
    ('Fernando', 'Moya García', 'fernando.moya@example.com', 'Toledo', '1980-01-01'),
    ('Marta', 'Rivas Silva', 'marta.rivas@example.com', 'San Sebastián', '1996-07-30'),
    ('Diego', 'Paniagua Córdova', 'diego.paniagua@example.com', 'Albacete', '1988-04-21'),
    ('Patricia', 'Ortega Fernández', 'patricia.ortega@example.com', 'Logroño', '1997-08-05'),
    ('Javier', 'Torrente Ramos', 'javier.torrente@example.com', 'Burgos', '1984-09-17'),
    ('Nuria', 'Salinas Reyes', 'nuria.salinas@example.com', 'Santiago de Compostela', '1991-05-13'),
    ('Victor', 'Delgado Pinto', 'victor.delgado@example.com', 'Gijón', '1986-02-09');
