CREATE TABLE 'futbol'.'jugadores (
'IDENTIFICADOR' INT NOT NULL AUTO_INCREMENT, 
'nombre' VARCHAR(255) NOT NULL,
'nombre' VARCHAR(255) NOT NULL,
'nombre' VARCHAR(255) NOT NULL,
'nombre' VARCHAR(255) NOT NULL,